---
blank_issues_enabled: true
contact_links:
  - name: Report a bug with the Home Assistant IPP integration
    url: https://github.com/home-assistant/core/issues/new?template=bug_report.yml&integration_name=Internet%20Printing%20Protocol%20(IPP)&integration_link=https://www.home-assistant.io/integrations/ipp
    about: Please report issues with the Home Assistant IPP integration in the Home Assistant core repository unless a developer told you otherwise.
  - name: I have a question or need support
    url: https://www.home-assistant.io/help
    about: We use GitHub for tracking bugs, check the Home Assistant website for resources on getting help.
  - name: Feature Request
    url: https://community.home-assistant.io/c/feature-requests
    about: Please use the Home Assistant Community Forum for making feature requests.
